version: '3.9'

services:
  frontend:
    build: frontend/.
    ports:
      - "8080:8080"
    networks:
      - rewind_network
  backend:
    build: backend/.
    ports:
      - "3000:3000"
    networks:
      - rewind_network

networks:
  rewind_network:
    driver: bridge